

services:
  # Container do PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/gguise/albumcompartilhado:latest
    container_name: eternizar-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - app-network

  # Container do Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  # Container do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: eternizar-db
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/data:/var/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
